# Generated by Django 4.2 on 2023-11-22 14:51

from django.db import migrations, models
import django.db.models.deletion
import polls.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[polls.models.length_validator, polls.models.username_validator])),
                ('password', models.CharField(max_length=60, validators=[polls.models.length_validator])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('hint', models.CharField(max_length=50)),
                ('hint_answer', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, validators=[polls.models.length_validator, polls.models.username_validator])),
                ('password', models.CharField(max_length=60, validators=[polls.models.length_validator])),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('hint', models.CharField(max_length=50)),
                ('hint_answer', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('productID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('ID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('productID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sellerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.seller'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressID', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('userID', 'street', 'city', 'state', 'zipcode'), name='unique_address'),
        ),
    ]
