# Generated by Django 4.2 on 2023-12-07 04:10

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=60, validators=[polls.models.length_validator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[polls.models.length_validator, polls.models.username_validator]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=60, validators=[polls.models.length_validator]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[polls.models.length_validator, polls.models.username_validator]),
        ),
    ]
