# Generated by Django 4.2 on 2023-12-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
