# Generated by Django 4.2 on 2023-12-08 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_product_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
