# Generated by Django 4.2 on 2024-03-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_address_payment_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
