# Generated by Django 4.2 on 2024-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0011_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=100),
        ),
    ]
