# Generated by Django 4.2.6 on 2023-10-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(default="account", max_length=16, unique=True),
                ),
                (
                    "password",
                    models.CharField(default="password", max_length=16, unique=True),
                ),
                ("seller", models.BooleanField(default=False)),
            ],
        ),
    ]
