name: Deploy to AWS EC2

on:
  push:
    branches:
      - pengxiangli

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./CartCove
        file: ./CartCove/Dockerfile
        push: true
        tags: pengxiangli/cartcove:latest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-2'

    - name: Decode SSH Key
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY_BASE64 }}
      run: |
        echo "$SSH_KEY" | base64 -d > $HOME/ssh_key.pem
        chmod 600 $HOME/ssh_key.pem

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: $HOME/ssh_key.pem
        debug: true
        script: |
          docker pull pengxiangli/cartcove:latest
          docker stop cartcove || true
          docker run -d --name cartcove -p 8000:8000 pengxiangli/cartcove:latest
